name: CI
on:
  push:
    branches:
      - 'auto-cadence-upgrade/(('
      - staging
      - trying
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
    pull request:
      branches:
        - master
        - 'auto-cadence-upgrade/**'
        - 'feature/**'
        - 'v[0-9]+.[0-9]'
env:
  GO_VERSION: 1.19

concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number || github.run_id}}
  cancel-in-progress: true
jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        dir: [./, ./integration/, ./crypto/]
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true
      - name: Build relic
        run: make crypto_setup_gopath
      - name: Run go generate
        run: go generate
        working-directory: ${{matrix.ir}}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          #Required: the version of golangci-lint is required and must be specified without patch version. We always use the latest patch.
          version: v1.47
          args: -v --build-tags relic
          working-directory: ${{matrix.dir}}
          # https://github.com/golangci/golangci-lint-action/issues/244
          skip-cache: true

        shell-check:
          name: ShellCheck
          runs-on: ubuntu-latest
          steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Run Shellcheck
              uses: ludeeus/actions-shellcheck@203a3fd018dfe73f8ae7e3aa8da2c149a5f41c33
              with:
                scandir: './crypto'
                ignore: 'relic''

